<?php
/**
 * Copyright 2018 Klarna Bank AB (publ)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @category   Klarna
 * @package    Klarna_Kco
 * @author     Marcin Dancewicz <marcin.dancewicz@klarna.com>
 * @author     Jason Grim <jason.grim@klarna.com>
 */

/**
 * Klarna admin checkout template
 */
?>

<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3><?php echo $this->getHeaderText() ?></h3></td>
            <td class="form-buttons">
                <?php echo $this->getButtonsHtml() ?>
            </td>
        </tr>
    </table>
</div>
<?php echo $this->getKlarnaHtml(); ?>

<script type="text/javascript">
    //<![CDATA[
    window._klarnaCheckout(function (api) {
        var onChangeCalled = false;
        api.on({
            'change': function (data) {
                if (true === onChangeCalled) {
                    api.suspend();
                    alert("<?php echo $this->__('Address updates are not allowed for admin orders.\nYour changes will be reset.'); ?>");
                    window.location = window.location;
                }
                onChangeCalled = true;
            }
        });
    });
    //]]>
</script>
